Repository microsoft/MLOS, pull requests merged in 2023-10, with the labels that each got.

#525 Client-facing storage API
  mlos_bench/mlos_bench/storage/__init__.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/base_trial_data.py
  mlos_bench/mlos_bench/storage/sql/experiment_data.py
  mlos_bench/mlos_bench/storage/sql/storage.py
  mlos_bench/mlos_bench/storage/sql/trial_data.py
  mlos_bench/mlos_bench/storage/storage_factory.py
Labels: ready for review

#528 Provide configurable ability for locally executed scripts to abort early
  mlos_bench/mlos_bench/config/schemas/services/local/local-exec-service-subschema.json
  mlos_bench/mlos_bench/services/local/local_exec.py
  mlos_bench/mlos_bench/services/types/local_exec_type.py
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/local_exec_service-invalid-abort_on_error.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/local_exec_service-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/local_exec_service-partial.jsonc
  mlos_bench/mlos_bench/tests/services/local/local_exec_test.py
  mlos_bench/mlos_bench/tests/services/local/mock/mock_local_exec_service.py
Labels: ready for review

#529 Misc bug fixes and improvements
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/services/local/local_exec.py
  mlos_bench/mlos_bench/services/local/temp_dir_context.py
  mlos_bench/mlos_bench/tests/config/globals/global_test_config.jsonc
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
  mlos_bench/mlos_bench/tests/services/config_persistence_test.py
  mlos_bench/mlos_bench/tests/services/local/local_exec_test.py
Labels: ready for review

#538 bugfix: allow non-numeric values in trial results data
  mlos_bench/mlos_bench/storage/sql/experiment_data.py
Labels: bug, ready for review

#548 Add unit tests for multi-score updates. Allow non-numeric metrics in storage type annotations.
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/tests/storage/exp_load_test.py
Labels: ready for review

#551 Fix the nested service inclusion issue + add unit tests
  mlos_bench/mlos_bench/environments/base_environment.py
  mlos_bench/mlos_bench/services/base_fileshare.py
  mlos_bench/mlos_bench/services/base_service.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/services/local/local_exec.py
  mlos_bench/mlos_bench/services/local/temp_dir_context.py
  mlos_bench/mlos_bench/services/remote/azure/azure_auth.py
  mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py
  mlos_bench/mlos_bench/services/remote/azure/azure_services.py
  mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_2.jsonc
  mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_3.jsonc
  mlos_bench/mlos_bench/tests/environments/composite_env_service_test.py
  mlos_bench/mlos_bench/tests/services/local/mock/mock_local_exec_service.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_auth_service.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_fileshare_service.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_remote_exec_service.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_vm_service.py
Labels: ready for review

#552 devcontainer Fixups
  .devcontainer/Dockerfile
  .devcontainer/build/build-devcontainer.sh
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/scripts/common/prep-deps-files.sh
  .devcontainer/scripts/run-devcontainer.sh
  .github/workflows/devcontainer.yml
Labels: ready for review

#549 Accept non-string categoricals
  mlos_bench/mlos_bench/config/schemas/tunables/tunable-params-schema.json
  mlos_bench/mlos_bench/tests/config/schemas/tunable-params/test-cases/good/full/full-tunable-params-test.jsonc
  mlos_bench/mlos_bench/tests/conftest.py
  mlos_bench/mlos_bench/tests/tunables/test_tunable_categoricals.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/mlos_bench/tunables/tunable_groups.py
Labels: ready for review

#510 Add SSH Support
  .cspell.json
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/scripts/run-devcontainer.sh
  .github/workflows/devcontainer.yml
  .vscode/settings.json
  conda-envs/mlos-3.10.yml
  conda-envs/mlos-3.11.yml
  conda-envs/mlos-3.8.yml
  conda-envs/mlos-3.9.yml
  conda-envs/mlos-windows.yml
  conda-envs/mlos.yml
  mlos_bench/mlos_bench/config/schemas/services/remote/ssh/common-defs-subschemas.json
  mlos_bench/mlos_bench/config/schemas/services/remote/ssh/ssh-fileshare-service-subschema.json
  mlos_bench/mlos_bench/config/schemas/services/remote/ssh/ssh-host-service-subschema.json
  mlos_bench/mlos_bench/config/schemas/services/service-schema.json
  mlos_bench/mlos_bench/services/remote/ssh/__init__.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_fileshare.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_host_service.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_service.py
  mlos_bench/mlos_bench/tests/__init__.py
  mlos_bench/mlos_bench/tests/config/__init__.py
  mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/ssh_fileshare_service-bad-port-type.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/ssh_host_service-bad-known_hosts-type.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/ssh_host_service-bad_request_timeout.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/unhandled/ssh_fileshare_service-extras.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/unhandled/ssh_host_service-extras.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/ssh_fileshare_service-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/ssh_host_service-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/ssh_fileshare_service-partial.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/ssh_host_service-partial.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test_services_schemas.py
  mlos_bench/mlos_bench/tests/conftest.py
  mlos_bench/mlos_bench/tests/event_loop_context_test.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/.gitignore
  mlos_bench/mlos_bench/tests/services/remote/ssh/Dockerfile
  mlos_bench/mlos_bench/tests/services/remote/ssh/README.md
  mlos_bench/mlos_bench/tests/services/remote/ssh/__init__.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/conftest.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/docker-compose.yml
  mlos_bench/mlos_bench/tests/services/remote/ssh/down.sh
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_fileshare.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_host_service.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_service.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/up.sh
  mlos_bench/setup.py
  setup.cfg
Labels: ready for review

#562 Add checks for test count
  .github/workflows/devcontainer.yml
  Makefile
Labels: WIP

#571 Clean-up temp directories created in unit tests
  mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_2.jsonc
  mlos_bench/mlos_bench/tests/config/services/local/mock/mock_local_exec_service_3.jsonc
  mlos_bench/mlos_bench/tests/environments/composite_env_service_test.py
Labels: ready for review
