Repository microsoft/MLOS, pull requests merged in 2023-04, with the labels that each got.

#287 Workaround upstream conda release issue
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/extensions.json
Labels: bug, dependencies, ready for review

#298 Minimal SQL DB storage implementation
  .cspell.json
  mlos_bench/config/storage/duckdb.jsonc
  mlos_bench/config/storage/mysql.jsonc
  mlos_bench/config/storage/postgresql.jsonc
  mlos_bench/config/storage/sqlite.jsonc
  mlos_bench/db/osat.sql
  mlos_bench/mlos_bench/environment/base_environment.py
  mlos_bench/mlos_bench/environment/mock_env.py
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/optimizer/base_optimizer.py
  mlos_bench/mlos_bench/optimizer/convert_configspace.py
  mlos_bench/mlos_bench/optimizer/mlos_core_optimizer.py
  mlos_bench/mlos_bench/optimizer/mock_optimizer.py
  mlos_bench/mlos_bench/run_bench.py
  mlos_bench/mlos_bench/run_opt.py
  mlos_bench/mlos_bench/service/config_persistence.py
  mlos_bench/mlos_bench/storage/__init__.py
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/sql/__init__.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/storage/sql/storage.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/tests/conftest.py
  mlos_bench/mlos_bench/tests/environment/mock_env_test.py
  mlos_bench/mlos_bench/tests/optimizer/conftest.py
  mlos_bench/mlos_bench/tests/optimizer/llamatune_opt_test.py
  mlos_bench/mlos_bench/tests/optimizer/mock_opt_test.py
  mlos_bench/mlos_bench/tests/optimizer/opt_bulk_register_test.py
  mlos_bench/mlos_bench/tests/optimizer/toy_optimization_loop_test.py
  mlos_bench/mlos_bench/tests/service/remote/azure/azure_fileshare_test.py
  mlos_bench/mlos_bench/tests/storage/conftest.py
  mlos_bench/mlos_bench/tests/storage/exp_load_test.py
  mlos_bench/mlos_bench/tests/storage/trial_config_test.py
  mlos_bench/mlos_bench/tests/tunables/conftest.py
  mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_str_test.py
  mlos_bench/mlos_bench/tests/util_git_test.py
  mlos_bench/mlos_bench/tunables/covariant_group.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/mlos_bench/tunables/tunable_groups.py
  mlos_bench/mlos_bench/util.py
  mlos_bench/setup.py
  mlos_core/mlos_core/optimizers/__init__.py
  mlos_core/mlos_core/spaces/adapters/__init__.py
Labels: ready for review

#311 make resolve_path parameter handle lists of paths
  mlos_bench/mlos_bench/service/config_persistence.py
Labels: enhancement, ready for review

#312 No-op optimizer that runs a single benchmark with a given config
  mlos_bench/config/optimizers/one_shot_opt.jsonc
  mlos_bench/mlos_bench/optimizer/__init__.py
  mlos_bench/mlos_bench/optimizer/one_shot_optimizer.py
Labels: enhancement, ready for review

#310 Add a configuration for NULL storage (in-memory SQLite3).
  mlos_bench/config/storage/in-memory.jsonc
Labels: enhancement, ready for review
