Repository microsoft/MLOS, pull requests merged in 2023-09, with the labels that each got.

#503 Extract benchmark results straight from the local or remote stdout
  mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
  mlos_bench/mlos_bench/environments/local/local_env.py
  mlos_bench/mlos_bench/environments/remote/remote_env.py
  mlos_bench/mlos_bench/environments/script_env.py
  mlos_bench/mlos_bench/services/remote/azure/azure_services.py
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_fileshare_env-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/remote_env-full.jsonc
  mlos_bench/mlos_bench/tests/environments/local/local_env_stdout_test.py
  mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
Labels: ready for review

#508 CI fixups
  .github/workflows/devcontainer.yml
  Makefile
Labels: ready for review

#509 Fixups to commit message checks to only happen during PR pushes
  .github/workflows/devcontainer.yml
Labels: ready for review

#512 Forgot string interpolation prefix in AzureFileShareService exception message
  mlos_bench/mlos_bench/services/remote/azure/azure_fileshare.py
Labels: bug, good first issue, ready for review

#514 Minor fixes to make pylint happy and remove some pylint exceptions
  mlos_bench/mlos_bench/tests/services/remote/azure/azure_services_test.py
Labels: ready for review, tests

#511 No cache support for manual devcontainer build triggers
  .github/workflows/devcontainer.yml
Labels: ready for review

#513 Unit tests for combining the results of several `LocalEnv`s in one `CompositeEnv`
  mlos_bench/mlos_bench/tests/environments/local/__init__.py
  mlos_bench/mlos_bench/tests/environments/local/composite_local_env_test.py
  mlos_bench/mlos_bench/tests/environments/local/local_env_stdout_test.py
  mlos_bench/mlos_bench/tests/environments/local/local_env_telemetry_test.py
  mlos_bench/mlos_bench/tests/environments/local/local_env_test.py
  mlos_bench/mlos_bench/tests/environments/local/local_env_vars_test.py
Labels: ready for review, tests
