Repository microsoft/MLOS, pull requests merged in 2023-11, with the labels that each got.

#572 Fix pylint and mypy warnings
  mlos_bench/mlos_bench/event_loop_context.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_host_service.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_service.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/fixtures.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_service.py
Labels: ready for review

#574 Update json schema to the actual parameters of script_env
  mlos_bench/mlos_bench/config/schemas/environments/common-environment-subschemas.json
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_script_params_mapping.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/local_env-bad_script_params_mapping_type.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/local_env-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/remote_env-full.jsonc
Labels: ready for review

#573 Do not pass all params as script env variables by default
  mlos_bench/mlos_bench/environments/script_env.py
Labels: ready for review

#570 Parallelize ssh tests
  .cspell.json
  .vscode/launch.json
  conftest.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_host_service.py
  mlos_bench/mlos_bench/tests/__init__.py
  mlos_bench/mlos_bench/tests/conftest.py
  mlos_bench/mlos_bench/tests/environments/remote/conftest.py
  mlos_bench/mlos_bench/tests/environments/remote/test_ssh_env.py
  mlos_bench/mlos_bench/tests/event_loop_context_test.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/Dockerfile
  mlos_bench/mlos_bench/tests/services/remote/ssh/README.md
  mlos_bench/mlos_bench/tests/services/remote/ssh/__init__.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/conftest.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/docker-compose.yml
  mlos_bench/mlos_bench/tests/services/remote/ssh/fixtures.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_fileshare.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_host_service.py
  mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_service.py
  mlos_bench/setup.py
  setup.cfg
Labels: ready for review

#579 Clean-up temp files created by mlos_core optimizers
  .gitignore
  mlos_bench/mlos_bench/config/optimizers/mlos_core_smac.jsonc
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/tests/event_loop_context_test.py
  mlos_bench/mlos_bench/tests/optimizers/mlos_core_opt_smac_test.py
  mlos_core/mlos_core/optimizers/optimizer.py
Labels: ready for review

#520 SaaS Environment + Azure Flex DB configuration service
  mlos_bench/mlos_bench/config/environments/apps/mysql/mysql-tunables.jsonc
  mlos_bench/mlos_bench/config/environments/saas/azure-flex-db.jsonc
  mlos_bench/mlos_bench/config/schemas/environments/leaf-environment-subschemas.json
  mlos_bench/mlos_bench/config/schemas/environments/remote/saas-env-subschema.json
  mlos_bench/mlos_bench/config/schemas/services/remote/azure/azure-saas-service-subschema.json
  mlos_bench/mlos_bench/config/schemas/services/service-schema.json
  mlos_bench/mlos_bench/config/services/remote/azure/service-flex-mariadb.jsonc
  mlos_bench/mlos_bench/config/services/remote/azure/service-flex-mysql.jsonc
  mlos_bench/mlos_bench/config/services/remote/azure/service-flex-postgresql.jsonc
  mlos_bench/mlos_bench/environments/remote/__init__.py
  mlos_bench/mlos_bench/environments/remote/saas_env.py
  mlos_bench/mlos_bench/services/remote/azure/__init__.py
  mlos_bench/mlos_bench/services/remote/azure/azure_saas.py
  mlos_bench/mlos_bench/services/types/__init__.py
  mlos_bench/mlos_bench/services/types/remote_config_type.py
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/invalid/saas_env-invalid.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/bad/unhandled/saas_env-extras.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/full/saas_env-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/environments/test-cases/good/partial/saas_env-partial.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_flex_service-invalid-api.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/invalid/azure_flex_service-missing-provider.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/bad/unhandled/azure_flex_service-extras.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/full/azure_flex_service-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/services/test-cases/good/partial/azure_flex_service-partial.jsonc
Labels: ready for review

#524 Some documentation fixups
  CONTRIBUTING.md
  Makefile
  README.md
  SECURITY.md
  doc/copy-source-tree-docs.sh
  doc/requirements.txt
  doc/source/.gitignore
  doc/source/_static/llamatune-loop.png
  doc/source/conf.py
  doc/source/index.rst
  doc/source/installation.rst
  mlos_bench/README.md
  mlos_core/README.md
Labels: ready for review

#586 allow using all parameters in paths witout declaring them in `shell_env_params`
  mlos_bench/mlos_bench/environments/local/local_fileshare_env.py
  mlos_bench/mlos_bench/environments/script_env.py
Labels: ready for review

#587 Add unit tests for LocalFileShareEnv $var expansion in upload and download paths
  mlos_bench/mlos_bench/tests/environments/local/__init__.py
  mlos_bench/mlos_bench/tests/environments/local/local_fileshare_env_test.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_fileshare_service.py
Labels: ready for review

#593 Make FIO benchmark a configurable parameter
  mlos_bench/mlos_bench/config/environments/apps/fio/fio-post.jsonc
  mlos_bench/mlos_bench/config/environments/apps/fio/fio-pre.jsonc
  mlos_bench/mlos_bench/config/environments/apps/fio/fio.jsonc
Labels: ready for review

#596 Single schema definition support
  mlos_bench/mlos_bench/config/schemas/config_schemas.py
  mlos_bench/mlos_bench/config/schemas/mlos-bench-config-schema.json
  mlos_bench/mlos_bench/tests/config/schemas/cli/test_cli_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/environments/test_environment_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/globals/test_globals_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test_optimizer_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/services/test_services_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/storage/test_storage_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/tunable-params/test_tunable_params_schemas.py
  mlos_bench/mlos_bench/tests/config/schemas/tunable-values/test_tunable_values_schemas.py
Labels: ready for review, low priority

#605 Update schema docs to reflect new unified schema
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  mlos_bench/mlos_bench/config/schemas/README.md
Labels: documentation, WIP

#608 Allow specifying services in CLI args or top level cli config.
  mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
  mlos_bench/mlos_bench/config/schemas/mlos-bench-config-schema.json
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/services/types/__init__.py
  mlos_bench/mlos_bench/services/types/config_loader_type.py
  mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/min-services-items.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/wrong-services-type.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/good/full/full-cli.jsonc
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
Labels: ready for review
