Repository microsoft/MLOS, pull requests merged in 2024-01, with the labels that each got.

#623 Tunable fixups
  mlos_bench/mlos_bench/tests/tunables/test_tunable_categoricals.py
  mlos_bench/mlos_bench/tunables/tunable.py
Labels: bug, ready for review

#626 Pypi packaging
  .bumpversion.cfg
  .github/workflows/devcontainer.yml
  CONTRIBUTING.md
  MAINTAINING.md
  Makefile
  README.md
  conftest.py
  doc/source/conf.py
  mlos_bench/README.md
  mlos_bench/_version.py
  mlos_bench/setup.py
  mlos_core/README.md
  mlos_core/_version.py
  mlos_core/setup.py
  scripts/update-version.sh
Labels: ready for review

#628 Add support for storing the optimization targets and direction of an experiment
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/experiment_data.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/storage/sql/storage.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/tests/storage/conftest.py
  mlos_bench/mlos_bench/tests/storage/exp_data_test.py
  mlos_bench/mlos_bench/tests/storage/trial_data_test.py
Labels: ready for review

#632 Github Action syntax fixup
  .github/workflows/devcontainer.yml
Labels: ready for review, ci

#634 Add labels to the optimizer trends plot
  mlos_viz/mlos_viz/__init__.py
Labels: ready for review, mlos-viz

#630 Add more info on const_args vs. tunable_params; start the DEVNOTES
  mlos_bench/mlos_bench/DEVNOTES.md
  mlos_bench/mlos_bench/config/README.md
Labels: documentation, ready for review

#617 Support for special tunable values outside of the range
  .bumpversion.cfg
  doc/source/conf.py
  mlos_bench/_version.py
  mlos_bench/mlos_bench/config/environments/os/linux/runtime/linux-runtime-tunables.jsonc
  mlos_bench/mlos_bench/optimizers/convert_configspace.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/tests/conftest.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
  mlos_bench/mlos_bench/tests/optimizers/mock_opt_test.py
  mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
  mlos_bench/mlos_bench/tests/optimizers/toy_optimization_loop_test.py
  mlos_bench/mlos_bench/tests/tunables/conftest.py
  mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_str_test.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_core/_version.py
  mlos_core/mlos_core/__init__.py
  mlos_core/mlos_core/optimizers/flaml_optimizer.py
  mlos_core/mlos_core/optimizers/optimizer.py
  mlos_core/mlos_core/spaces/adapters/llamatune.py
  mlos_core/mlos_core/util.py
Labels: ready for review, mlos-bench

#638 Add unit tests for `MlosCoreoptimizer._to_df()` functionality; use special values in tunables
  mlos_bench/mlos_bench/optimizers/convert_configspace.py
  mlos_bench/mlos_bench/tests/optimizers/conftest.py
  mlos_bench/mlos_bench/tests/optimizers/mlos_core_opt_df_test.py
  mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
Labels: ready for review, tests, mlos-bench

#647 README documentation updates
  MAINTAINING.md
  README.md
  mlos_bench/README.md
  mlos_bench/mlos_bench/storage/README.md
  mlos_viz/README.md
Labels: documentation, ready for review

#650 Add `default_tunable_config_id` property to `ExperimentData`
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/sql/experiment_data.py
  mlos_bench/mlos_bench/tests/storage/exp_data_test.py
Labels: ready for review

#652 Remove mistakenly added columns
  mlos_bench/mlos_bench/storage/sql/schema.py
Labels: bug, ready for review

#651 Fixes to `max_iterations` calculation when `trial_config_repeat_count` is given.
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
Labels: bug, ready for review

#653 Address some pandas FuturesWarnings
  mlos_bench/mlos_bench/environments/local/local_env.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/storage/sql/common.py
Labels: ready for review

#633 Improve mlos-viz for multiple repeats of a config and add tests
  .bumpversion.cfg
  .cspell.json
  .github/workflows/build-dist-test.ps1
  Makefile
  doc/source/conf.py
  mlos_bench/_version.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/sql/experiment_data.py
  mlos_bench/mlos_bench/storage/sql/tunable_config_trial_group_data.py
  mlos_bench/mlos_bench/tests/storage/sql/__init__.py
  mlos_bench/mlos_bench/tests/storage/sql/fixtures.py
  mlos_bench/mlos_bench/tests/storage/trial_data_test.py
  mlos_core/_version.py
  mlos_viz/mlos_viz/__init__.py
  mlos_viz/mlos_viz/base.py
  mlos_viz/mlos_viz/dabl.py
  mlos_viz/mlos_viz/py.typed
  mlos_viz/mlos_viz/tests/README.md
  mlos_viz/mlos_viz/tests/__init__.py
  mlos_viz/mlos_viz/tests/conftest.py
  mlos_viz/mlos_viz/tests/test_base_plot.py
  mlos_viz/mlos_viz/tests/test_dabl_plot.py
  mlos_viz/mlos_viz/tests/test_mlos_viz.py
  mlos_viz/mlos_viz/util.py
Labels: enhancement, ready for review, tests, mlos-bench, mlos-viz
