Repository microsoft/MLOS, pull requests merged in 2024-03, with the labels that each got.

#695 Bump version: 0.5.0 → 0.5.1 to mark a stable version before the big changes (async Environment etc.)
  .bumpversion.cfg
  doc/source/conf.py
  mlos_bench/_version.py
  mlos_core/_version.py
Labels: ready for review

#697 Move config_space to base Optimizer property
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/optimizers/convert_configspace.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
Labels: ready for review

#699 Pin a devcontainer version to workaround library search path issue
  .devcontainer/Dockerfile
Labels: dependencies, ready for review, ci

#696 Typing tweaks
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/storage/util.py
  mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_distributions_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
  mlos_bench/mlos_bench/tunables/tunable.py
Labels: ready for review

#698 Add cardinality and size related properties to Tunables
  mlos_bench/mlos_bench/tests/tunables/test_tunables_size_props.py
  mlos_bench/mlos_bench/tunables/tunable.py
Labels: ready for review

#691 Pluggable Scheduler implementation
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/schedulers/__init__.py
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/schedulers/sync_scheduler.py
  mlos_bench/mlos_bench/tests/launcher_in_process_test.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
Labels: ready for review, mlos-bench

#690 Add GridSearch Optimizer support
  mlos_bench/mlos_bench/config/schemas/optimizers/optimizer-schema.json
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/invalid/grid_search_opt_invalid_max_iterations.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/unhandled/grid_search_opt_extra.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/grid_search_opt_full.jsonc
  mlos_bench/mlos_bench/tests/optimizers/grid_search_optimizer_test.py
  mlos_bench/mlos_bench/tunables/tunable_groups.py
Labels: ready for review

#709 Factor out the functionality of best config tracking into a separate abstract Optimizer class
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/optimizers/mock_optimizer.py
  mlos_bench/mlos_bench/optimizers/track_best_optimizer.py
Labels: ready for review

#708 Roll back forceful assignment of PATH when invoking a local process
  mlos_bench/mlos_bench/services/local/local_exec.py
Labels: bug, ready for review

#707 A function for a popular `None if value is None else func(value)` code pattern
  mlos_bench/mlos_bench/environments/mock_env.py
  mlos_bench/mlos_bench/optimizers/convert_configspace.py
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/optimizers/mock_optimizer.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_service.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/tests/storage/trial_telemetry_test.py
  mlos_bench/mlos_bench/tests/util_nullable_test.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/mlos_bench/util.py
Labels: ready for review

#710 Pluggable Scheduler
  .vscode/settings.json
  mlos_bench/mlos_bench/config/schedulers/sync_scheduler.jsonc
  mlos_bench/mlos_bench/config/schemas/config_schemas.py
  mlos_bench/mlos_bench/config/schemas/mlos-bench-config-schema.json
  mlos_bench/mlos_bench/config/schemas/schedulers/scheduler-schema.json
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/bad/invalid/invalid-scheduler-class.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/bad/invalid/sync_sched-bad-repeat.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/bad/invalid/sync_sched-empty-config.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/bad/unhandled/sync_sched-extra.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/good/full/sync_sched-full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/good/partial/sync_sched-partial.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test_scheduler_schemas.py
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
  mlos_bench/mlos_bench/util.py
Labels: ready for review, mlos-bench

#717 Add more tests for Scheduler configurations (CLI and JSON)
  mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
  mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
Labels: ready for review, mlos-bench

#716 UTC datetime handling improvements
  mlos_bench/mlos_bench/environments/base_environment.py
  mlos_bench/mlos_bench/environments/local/local_env.py
  mlos_bench/mlos_bench/environments/remote/remote_env.py
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/schedulers/sync_scheduler.py
  mlos_bench/mlos_bench/services/remote/azure/azure_auth.py
  mlos_bench/mlos_bench/storage/base_trial_data.py
  mlos_bench/mlos_bench/storage/sql/common.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/storage/sql/trial_data.py
  mlos_bench/mlos_bench/tests/__init__.py
  mlos_bench/mlos_bench/tests/environments/local/composite_local_env_test.py
  mlos_bench/mlos_bench/tests/environments/local/local_env_telemetry_test.py
  mlos_bench/mlos_bench/tests/storage/exp_load_test.py
  mlos_bench/mlos_bench/tests/storage/sql/fixtures.py
  mlos_bench/mlos_bench/tests/storage/trial_config_test.py
  mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py
  mlos_bench/mlos_bench/tests/storage/trial_telemetry_test.py
  mlos_bench/mlos_bench/tests/test_with_alt_tz.py
  mlos_bench/mlos_bench/util.py
Labels: ready for review

#713 Rename `max_iterations` to `max_suggestions` and track in Optimizer `.suggest()` instead of `.register()`
  mlos_bench/README.md
  mlos_bench/mlos_bench/config/cli/azure-redis-opt.jsonc
  mlos_bench/mlos_bench/config/experiments/README.md
  mlos_bench/mlos_bench/config/optimizers/mlos_core_default_opt.jsonc
  mlos_bench/mlos_bench/config/optimizers/mlos_core_flaml.jsonc
  mlos_bench/mlos_bench/config/optimizers/mlos_core_smac.jsonc
  mlos_bench/mlos_bench/config/optimizers/mock_opt.jsonc
  mlos_bench/mlos_bench/config/schemas/optimizers/optimizer-schema.json
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/optimizers/mock_optimizer.py
  mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/schedulers/sync_scheduler.py
  mlos_bench/mlos_bench/tests/config/globals/global_test_config.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/invalid/grid_search_opt_invalid_max_iterations.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/invalid/missing_opt_class_config.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/invalid/mlos_opt_smac_bad_probability.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/unhandled/mlos_opt_smac_llamatune_extra.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/bad/unhandled/mock_opt_extra_outer.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/grid_search_opt_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/mlos_opt_flaml_null_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/mlos_opt_random_identity_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/mlos_opt_smac_llamatune_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/mlos_opt_smac_null_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/mock_opt_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/full/one_shot_opt_full.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/partial/mlos_opt_smac_llamatune_partial.jsonc
  mlos_bench/mlos_bench/tests/launcher_in_process_test.py
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
  mlos_bench/mlos_bench/tests/optimizers/conftest.py
  mlos_bench/mlos_bench/tests/optimizers/grid_search_optimizer_test.py
  mlos_bench/mlos_bench/tests/optimizers/llamatune_opt_test.py
  mlos_bench/mlos_bench/tests/optimizers/mlos_core_opt_df_test.py
  mlos_bench/mlos_bench/tests/optimizers/mlos_core_opt_smac_test.py
Labels: ready for review, mlos-bench

#719 Add `max_trials` scheduler config parameter
  mlos_bench/mlos_bench/config/schedulers/sync_scheduler.jsonc
  mlos_bench/mlos_bench/config/schemas/schedulers/scheduler-schema.json
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/schedulers/sync_scheduler.py
  mlos_bench/mlos_bench/tests/config/schemas/schedulers/test-cases/good/full/sync_sched-full.jsonc
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
Labels: ready for review, mlos-bench

#724 bugfix: handle `-Inf` in `try_parse_val()` function
  mlos_bench/mlos_bench/tests/util_try_parse_test.py
  mlos_bench/mlos_bench/util.py
Labels: bug, ready for review
