Repository microsoft/MLOS, pull requests merged in 2024-12, with the labels that each got.

#889 Fix storage API failing to return DF for experiments without any tunables
  mlos_bench/mlos_bench/storage/sql/common.py
  mlos_bench/mlos_bench/tests/storage/exp_data_test.py
Labels: ready for review

#887 More documentation updates
  Makefile
  README.md
  doc/source/conf.py
  doc/source/index.rst
  mlos_bench/README.md
  mlos_bench/mlos_bench/__init__.py
  mlos_bench/mlos_bench/config/__init__.py
  mlos_bench/mlos_bench/services/types/authenticator_type.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/sql/common.py
  mlos_core/README.md
  mlos_core/mlos_core/__init__.py
  mlos_core/mlos_core/data_classes.py
  mlos_core/mlos_core/spaces/converters/__init__.py
  mlos_core/mlos_core/spaces/converters/flaml.py
  mlos_viz/README.md
  mlos_viz/mlos_viz/__init__.py
Labels: documentation, ready for review

#890 Allow loading configs from JSON strings and test with new docstrings for tunables
  mlos_bench/mlos_bench/config/__init__.py
  mlos_bench/mlos_bench/environments/__init__.py
  mlos_bench/mlos_bench/environments/base_environment.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/services/types/config_loader_type.py
  mlos_bench/mlos_bench/storage/__init__.py
  mlos_bench/mlos_bench/storage/base_experiment_data.py
  mlos_bench/mlos_bench/storage/base_trial_data.py
  mlos_bench/mlos_bench/storage/base_tunable_config_data.py
  mlos_bench/mlos_bench/storage/base_tunable_config_trial_group_data.py
  mlos_bench/mlos_bench/storage/sql/__init__.py
  mlos_bench/mlos_bench/storage/storage_factory.py
  mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
  mlos_bench/mlos_bench/tests/services/config_persistence_test.py
  mlos_bench/mlos_bench/tunables/__init__.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/mlos_bench/tunables/tunable_groups.py
  mlos_core/mlos_core/spaces/__init__.py
  mlos_core/mlos_core/spaces/converters/__init__.py
Labels: ready for review

#896 make docstring test work in all environments
  conftest.py
  mlos_bench/mlos_bench/storage/__init__.py
Labels: bug, ready for review, tests, mlos-bench

#894 Doc linklint fixups
  Makefile
  doc/nginx-default.conf
  doc/source/index.rst
  mlos_bench/mlos_bench/__init__.py
  mlos_bench/mlos_bench/config/__init__.py
  mlos_bench/mlos_bench/environments/__init__.py
  mlos_bench/mlos_bench/run.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_core/mlos_core/__init__.py
Labels: ready for review
