Repository microsoft/MLOS, pull requests merged in 2025-01, with the labels that each got.

#908 Remove use of yq
  Makefile
  conda-envs/mlos-3.10.yml
  conda-envs/mlos-3.11.yml
  conda-envs/mlos-3.12.yml
  conda-envs/mlos-3.13.yml
  conda-envs/mlos-windows.yml
  conda-envs/mlos.yml
Labels: ready for review

#906 Storage schema evolution support
  .pre-commit-config.yaml
  Makefile
  conda-envs/mlos-3.10.yml
  conda-envs/mlos-3.11.yml
  conda-envs/mlos-3.12.yml
  conda-envs/mlos-3.13.yml
  conda-envs/mlos-windows.yml
  conda-envs/mlos.yml
  doc/source/conf.py
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/sql/alembic.ini
  mlos_bench/mlos_bench/storage/sql/alembic/README.md
  mlos_bench/mlos_bench/storage/sql/alembic/env.py
  mlos_bench/mlos_bench/storage/sql/alembic/script.py.mako
  mlos_bench/mlos_bench/storage/sql/alembic/versions/d2a708351ba8_add_alembic.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/storage/sql/storage.py
  mlos_bench/pyproject.toml
  mlos_bench/setup.py
  setup.cfg
Labels: ready for review

#911 speed improvement on licenseheaders pre-commit partial files run
  .pre-commit-config.yaml
Labels: ready for review, dev-env

#910 Minor tweaks to the revision script template to avoid some future linting fixups
  mlos_bench/mlos_bench/storage/sql/alembic/script.py.mako
Labels: ready for review

#909 Ignore the latest reformat revision from git blame
  .git-blame-ignore-revs
Labels: ready for review

#907 Add trial_runner_id column
  mlos_bench/mlos_bench/storage/sql/alembic.ini
  mlos_bench/mlos_bench/storage/sql/alembic/README.md
  mlos_bench/mlos_bench/storage/sql/alembic/env.py
  mlos_bench/mlos_bench/storage/sql/alembic/versions/f83fb8ae7fc4_add_trial_runner_id_column.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/tests/storage/test_storage_schemas.py
Labels: ready for review

#913 New release 0.6.2
  .bumpversion.cfg
  doc/source/version.py
  mlos_bench/mlos_bench/version.py
  mlos_core/mlos_core/version.py
  mlos_viz/mlos_viz/version.py
Labels: ready for review

#914 VSCode Tweaks
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/settings.json
Labels: ready for review

#720 Introduce TrialRunner Abstraction
  conftest.py
  doc/source/conf.py
  mlos_bench/mlos_bench/config/schemas/cli/cli-schema.json
  mlos_bench/mlos_bench/environments/base_environment.py
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/schedulers/base_scheduler.py
  mlos_bench/mlos_bench/schedulers/sync_scheduler.py
  mlos_bench/mlos_bench/schedulers/trial_runner.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/services/types/config_loader_type.py
  mlos_bench/mlos_bench/storage/__init__.py
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/base_trial_data.py
  mlos_bench/mlos_bench/storage/sql/common.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/storage/sql/trial_data.py
  mlos_bench/mlos_bench/tests/__init__.py
  mlos_bench/mlos_bench/tests/config/cli/test-cli-config.jsonc
  mlos_bench/mlos_bench/tests/config/cli/test_load_cli_config_examples.py
  mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/bad/invalid/min-trial-runners-count.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/cli/test-cases/good/full/full-cli.jsonc
  mlos_bench/mlos_bench/tests/environments/composite_env_test.py
  mlos_bench/mlos_bench/tests/environments/include_tunables_test.py
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
  mlos_bench/mlos_bench/tests/storage/__init__.py
  mlos_bench/mlos_bench/tests/storage/exp_data_test.py
  mlos_bench/mlos_bench/tests/storage/sql/fixtures.py
  mlos_bench/mlos_bench/tests/storage/test_storage_schemas.py
  mlos_bench/mlos_bench/tests/storage/trial_config_test.py
  mlos_bench/mlos_bench/tests/storage/trial_data_test.py
  mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py
Labels: ready for review

#921 use named constants instead of string literals when serializing Status values for storage
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/trial.py
Labels: ready for review, mlos-bench, refactor

#923 Create Trial with Status that matches Storage backend
  mlos_bench/mlos_bench/storage/base_storage.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/storage/sql/trial.py
  mlos_bench/mlos_bench/tests/storage/trial_schedule_test.py
Labels: bug, ready for review, tests

#922 Remove + operators from multiline string concats
  mlos_bench/mlos_bench/tests/launcher_parse_args_test.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
  mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
Labels: ready for review, low priority, refactor

#925 Update asyncssh
  mlos_bench/setup.py
Labels: ready for review

#928 mdformat pre-commit rules
  .github/pull_request_template.md
  .pre-commit-config.yaml
  CONTRIBUTING.md
  MAINTAINING.md
  README.md
  SECURITY.md
  doc/README.md
  mlos_bench/README.md
  mlos_bench/mlos_bench/config/services/remote/azure/scripts/setup-rg/README.md
  mlos_bench/mlos_bench/environments/README.md
  mlos_bench/mlos_bench/services/README.md
  mlos_bench/mlos_bench/services/remote/azure/README.md
  mlos_bench/mlos_bench/storage/README.md
  mlos_bench/mlos_bench/storage/sql/alembic/README.md
  mlos_bench/mlos_bench/tests/services/remote/ssh/README.md
  mlos_core/README.md
  mlos_core/mlos_core/spaces/adapters/README.md
Labels: ready for review, ci, refactor

#929 Enable pre-commit autoupdate PRs
  .pre-commit-config.yaml
Labels: ready for review, ci

#931 Schema changes example for mlos_benchd service
  mlos_bench/mlos_bench/environments/status.py
  mlos_bench/mlos_bench/storage/sql/alembic/README.md
  mlos_bench/mlos_bench/storage/sql/alembic/versions/8928a401115b_adding_experiment_table_columns_to_.py
  mlos_bench/mlos_bench/storage/sql/schema.py
  mlos_bench/mlos_bench/tests/storage/test_storage_schemas.py
Labels: ready for review

#933 Fixups for running pytest via VSCode
  mlos_bench/mlos_bench/optimizers/__init__.py
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test-cases/good/partial/grid_search_opt_minimal.jsonc
  mlos_bench/mlos_bench/tests/config/schemas/optimizers/test_optimizer_schemas.py
Labels: bug, ready for review

#930 Json Checking
  .pre-commit-config.yaml
  .prettierrc
Labels: ready for review, tests, ci

#932 Pyright Improvements
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  conda-envs/mlos.yml
  doc/source/conf.py
  mlos_bench/mlos_bench/environments/mock_env.py
  mlos_bench/mlos_bench/optimizers/mock_optimizer.py
  mlos_bench/mlos_bench/services/base_service.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_fileshare.py
  mlos_bench/mlos_bench/services/remote/ssh/ssh_host_service.py
  mlos_bench/mlos_bench/services/types/authenticator_type.py
  mlos_bench/mlos_bench/services/types/bound_method.py
  mlos_bench/mlos_bench/services/types/config_loader_type.py
  mlos_bench/mlos_bench/services/types/host_ops_type.py
  mlos_bench/mlos_bench/services/types/host_provisioner_type.py
  mlos_bench/mlos_bench/services/types/local_exec_type.py
  mlos_bench/mlos_bench/services/types/network_provisioner_type.py
  mlos_bench/mlos_bench/services/types/os_ops_type.py
  mlos_bench/mlos_bench/services/types/remote_config_type.py
  mlos_bench/mlos_bench/services/types/remote_exec_type.py
  mlos_bench/mlos_bench/services/types/vm_provisioner_type.py
  mlos_bench/mlos_bench/storage/sql/experiment.py
  mlos_bench/mlos_bench/tests/environments/composite_env_service_test.py
  mlos_bench/mlos_bench/tests/event_loop_context_test.py
  mlos_bench/mlos_bench/tests/launcher_run_test.py
  mlos_bench/mlos_bench/tests/services/mock_service.py
  mlos_bench/mlos_bench/tests/services/remote/mock/mock_vm_service.py
  mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_distributions_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_slice_references_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_assign_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_copy_test.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/setup.py
  mlos_core/mlos_core/__init__.py
  mlos_core/mlos_core/optimizers/__init__.py
  mlos_core/mlos_core/optimizers/bayesian_optimizers/smac_optimizer.py
  mlos_core/mlos_core/spaces/adapters/__init__.py
  mlos_core/mlos_core/spaces/adapters/llamatune.py
  mlos_core/mlos_core/spaces/converters/flaml.py
  mlos_core/mlos_core/spaces/converters/util.py
  mlos_core/mlos_core/tests/__init__.py
  mlos_core/mlos_core/tests/optimizers/optimizer_test.py
  mlos_core/mlos_core/tests/spaces/adapters/space_adapter_factory_test.py
  mlos_core/mlos_core/tests/spaces/spaces_test.py
  mlos_core/setup.py
  mlos_viz/mlos_viz/base.py
  mlos_viz/setup.py
  pyproject.toml
Labels: ready for review

#934 Temporarily workaround llamatune issues with numpy>=2.0
  mlos_core/setup.py
Labels: bug, dependencies, ready for review

#912 Various documentation improvements
  .cspell.json
  doc/nginx-docker.sh
  doc/source/conf.py
  doc/source/index.rst
  mlos_bench/mlos_bench/__init__.py
  mlos_bench/mlos_bench/config/__init__.py
  mlos_bench/mlos_bench/config/schemas/__init__.py
  mlos_bench/mlos_bench/environments/__init__.py
  mlos_bench/mlos_bench/environments/base_environment.py
  mlos_bench/mlos_bench/environments/composite_env.py
  mlos_bench/mlos_bench/environments/local/local_env.py
  mlos_bench/mlos_bench/environments/local/local_fileshare_env.py
  mlos_bench/mlos_bench/environments/mock_env.py
  mlos_bench/mlos_bench/environments/remote/remote_env.py
  mlos_bench/mlos_bench/environments/script_env.py
  mlos_bench/mlos_bench/launcher.py
  mlos_bench/mlos_bench/optimizers/__init__.py
  mlos_bench/mlos_bench/optimizers/base_optimizer.py
  mlos_bench/mlos_bench/optimizers/convert_configspace.py
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/optimizers/manual_optimizer.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/optimizers/mock_optimizer.py
  mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
  mlos_bench/mlos_bench/optimizers/track_best_optimizer.py
  mlos_bench/mlos_bench/services/config_persistence.py
  mlos_bench/mlos_bench/services/local/local_exec.py
  mlos_bench/mlos_bench/services/types/config_loader_type.py
  mlos_bench/mlos_bench/services/types/local_exec_type.py
  mlos_bench/mlos_bench/storage/base_trial_data.py
  mlos_bench/mlos_bench/storage/base_tunable_config_data.py
  mlos_bench/mlos_bench/storage/base_tunable_config_trial_group_data.py
  mlos_bench/mlos_bench/storage/sql/__init__.py
  mlos_bench/mlos_bench/storage/util.py
  mlos_bench/mlos_bench/tests/environments/__init__.py
  mlos_bench/mlos_bench/tests/environments/base_env_test.py
  mlos_bench/mlos_bench/tests/environments/remote/test_ssh_env.py
  mlos_bench/mlos_bench/tests/optimizers/grid_search_optimizer_test.py
  mlos_bench/mlos_bench/tests/optimizers/opt_bulk_register_test.py
  mlos_bench/mlos_bench/tests/services/local/local_exec_python_test.py
  mlos_bench/mlos_bench/tests/services/local/mock/mock_local_exec_service.py
  mlos_bench/mlos_bench/tests/tunables/tunable_definition_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_distributions_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_distr_test.py
  mlos_bench/mlos_bench/tests/tunables/tunable_to_configspace_test.py
  mlos_bench/mlos_bench/tests/tunables/tunables_copy_test.py
  mlos_bench/mlos_bench/tunables/__init__.py
  mlos_bench/mlos_bench/tunables/covariant_group.py
  mlos_bench/mlos_bench/tunables/tunable.py
  mlos_bench/mlos_bench/tunables/tunable_groups.py
  mlos_bench/mlos_bench/tunables/tunable_types.py
  mlos_core/mlos_core/optimizers/__init__.py
  mlos_core/mlos_core/spaces/adapters/__init__.py
  mlos_core/mlos_core/spaces/adapters/adapter.py
  mlos_core/mlos_core/spaces/adapters/llamatune.py
  mlos_viz/mlos_viz/__init__.py
Labels: documentation, ready for review

#937 Allow sphinx resolution of Azure types again.
  doc/requirements.txt
  doc/source/conf.py
Labels: documentation, dependencies, ready for review

#942 mlos_bench.optimizers doc fixups from #912
  mlos_bench/mlos_bench/optimizers/__init__.py
  mlos_bench/mlos_bench/optimizers/grid_search_optimizer.py
  mlos_bench/mlos_bench/optimizers/mlos_core_optimizer.py
  mlos_bench/mlos_bench/optimizers/one_shot_optimizer.py
Labels: documentation, ready for review
